### ISSUE TITLE
About incorect portal key

### ISSUE THREAD

**Issue by RUSshy** [TheKronks/K_Relay#16]
In realmrelay i dont have the problem

So what could be wrong about that key 

In hello and reconnect you reed the key as a byte[], in java bytes are all signed, while in c# they are not

byte : 0->255
sbyte: -128->127

so your key becomes invalid

I checked and yes the key from realmrelay contains negative and positive values, while the one from krelay only positive value

So you have to correctly read/write the key as an signed byte array

Another thing:

when you enter a dungeon, the key isn't empty anymore, the key will always have a length of 32

32 x 8 = 256 bits

so here we go, you can represent the key as a BigInteger

sry bad english, hope it help

**Comment by TheKronks** [comment]
They're negative in Java because, like you mentioned, all bytes are signed, so if any byte as >126 it will become negative due to the last bit being a '1', and that's how negatives are encoded on signed types.
Java actually has it wrong here, but either way it doesn't matter because the bytes are being written exactly as they are read

**Comment by RUSshy** [comment]
Hmm, that is really frustrating i've been trying few things for weeks but nothing has worked yet

What are your ideas, plans, research about this issues?

**Comment by TheKronks** [comment]
I've never had that issue at all so I really can't say
How often is it happening for you?

**Comment by RUSshy** [comment]
im using a custom version of krelay, i added support for VPN and remote proxy

well if u dont have issue that means i did something wrong..

i think i know what could be wrong, once i fix it ill send a pull request with lot of usefull feature
