### ISSUE TITLE
MapCacher is useless

### ISSUE THREAD

**Issue by apemanzilla** [TheKronks/K_Relay#20]
Looking through the MapCacher source code it seems like all it does is collect data, never actually sending it to the client like it says it does. I can try and make a functional version if you want.

**Comment by TheKronks** [comment]
Yeah looks like it was never finished? I'll remove it unless you do want to work on it.

**Comment by apemanzilla** [comment]
I'll work on a rewrite tomorrow or something. Seems like a really cool idea that never got finished.

**Comment by apemanzilla** [comment]
I've rewritten Map Cacher in #22, works pretty well.
