### ISSUE TITLE
Hello packet obfuscated fields

### ISSUE THREAD

**Issue by apemanzilla** [TheKronks/K_Relay#24]
Is there a reason that the hello packet doesn't use the real names for the fields instead of `obf#`?

Here's the real names:

![Screenshot](https://i.imgur.com/lVOj7RK.png)

**Comment by TheKronks** [comment]
At the time we didn't have access to the unobfuscated client, although, I thought I had already made those changes to the names. Better late than never I guess

**Comment by TheKronks** [comment]
Wait, yeah, those changes are in already
