### ISSUE TITLE
ParsingExtensions.cs fails to parse floats on Finnish Windows

### ISSUE THREAD

**Issue by Sose** [TheKronks/K_Relay#26]
Could've made a pull request but I'm not very familiar with git yet..

float.Parse() can fail on locales where decimal numbers are represented as "12,34" instead of "12.34" (comma vs dot). It does atleast on Finnish Windows.

Easy fix that seemed to work for me: change Lib K Relay / GameData / ParsingExtensions.cs / ParseFloat to:

`return float.Parse(input, System.Globalization.CultureInfo.InvariantCulture);`

**Comment by apemanzilla** [comment]
Oversight on my part, localization is hard. I'll make a PR with your change.

**Comment by apemanzilla** [comment]
For future reference, small changes like these can be made from the GitHub site which will automatically create your own branch and a PR for you.

**Comment by TheKronks** [comment]
I merged apemanzilla's commit.
