### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by thatguy2388** [TheKronks/K_Relay#29]
Hi Krazy! Can you please tell me how to use this new version? I used your previous ones but I can't seem to find the .exe on this one. Sorry for being dumb. :(

**Comment by apemanzilla** [comment]
This is just the source code for the project. You need to compile it using Visual Studio or another .NET IDE.

**Comment by thatguy2388** [comment]
Do I just load the k relay solution and then compile? And will any version of vs work? Thanks!

**Comment by apemanzilla** [comment]
VS 2015 works, not sure about older ones. And yes, load the solution and then do a full release build (select "Release" in the build drop down, then press ctrl + shift + b) and you'll find the files in `K-Relay/bin/Release`

**Comment by thatguy2388** [comment]
Got it! Downloading vs now. One last request if you're not busy good sir. Can you perhaps pastebin a sample plugin template for this version? Say I wanted to spam shoot packet or any packet by typing a command, how will I go about on doing that?

**Comment by apemanzilla** [comment]
Looking at the source code for existing plugins will be more helpful. The general idea is...

```c#
public class MyPlugin : IPlugin {
    public string GetName() { return "My Plugin"; }
    public string GetDescription() { return "Does cool stuff!"; }
    public string GetAuthor() { return "YourUsername"; }
    public string[] GetCommands() {
        return new string[] {
            "/myplugin"
        };
    }

    public void Initialize(Proxy proxy) {
        proxy.HookCommand("myplugin", OnCommand)
    }

    public void OnCommand(Client client, string command, string[] args) {
        PluginUtils.SendToClient(PluginUtils.CreateOryxNotification("My Plugin", "You ran a command!"));
    }
}
```

Keep in mind that when you're spamming `PlayerShoot` packets, 1) you will be kicked if you send them too fast and 2) you also need to send appropriate `EnemyHit` packets (which means you'll want to keep a list of enemies by capturing `Update` packets and do basic collision detection)

**Comment by thatguy2388** [comment]
Thanks! :)
