### ISSUE TITLE
Packet Structure Change In 27.7.X5

### ISSUE THREAD

**Issue by TheServer201** [TheKronks/K_Relay#32]
From Hello.as (http://pastebin.com/EyP84qBE) a new field named userToken is only on this version.
I created a small k relay like proxy in c and here the result (http://pastebin.com/Y29feNTq) you can see this new field at the end of the packet.

**Comment by PixelZerg** [comment]
@TheServer201 It's okay, looks like Einras is already on the case: https://github.com/TheKronks/K_Relay/pull/31

**Comment by TheKronks** [comment]
Thanks, yeah Eniras got it
