### ISSUE TITLE
Able to disable map caching?

### ISSUE THREAD

**Issue by Emerstone** [TheKronks/K_Relay#33]
Not so much the entire plugin I just don't want my client to reload a map whenever I go back to it without having to remove the autonexus.

**Comment by apemanzilla** [comment]
I can add that, but why? The client is going to reload the map when you walk near that area anyways

**Comment by Emerstone** [comment]
It's a little sketchy if I have half the map loaded in a screenshot when just coming back to a realm, or the nexus being fully loaded as well.

**Comment by apemanzilla** [comment]
Fair enough, I'll implement this when I have some spare time.
