### ISSUE TITLE
Packet Structure Change In 27.7.X6

### ISSUE THREAD

**Issue by TheServer201** [TheKronks/K_Relay#35]
Again some change with the new version 
- Hello packet loose the new field
- When conected with k relay the same thing append as when you are conneted with the 27.7.X5 client (for example when you switch a ring it back to the selection)
Here the log of my own proxy
http://pastebin.com/g9m11zbA

Edit. Some change I just found
https://puu.sh/rGwvx/7bc55be768.png
https://puu.sh/rGwyo/f899bd1671.png
https://puu.sh/rGwEA/580dc79166.png
https://puu.sh/rGwHS/11dcd4ebff.png
The new packet
https://puu.sh/rGwMJ/9869ff8d99.png
https://puu.sh/rGwQ8/8178f363cf.png

**Comment by Pyrolizrd** [comment]
Gonna post this here, looked through the Invswap and Aoeack packets via the decompiled .swf
Compared an older client to a post content update client, the only difference I could find was, on the 27th line for Invswap, or 22nd line for aoeack, these numbers are changed:
From the old invswap packet:
getproperty Qname(PrivateNamespace(null,"553"),"messages")

From the new invswap packet:
getproperty Qname(PrivateNamespace(null,"566"),"messages")

From the old aoeack packet: 
getproperty Qname(PrivateNamespace(null,"553"),"messages")

From the new aoeack packet:
getproperty Qname(PrivateNamespace(null,"566"),"messages")

Not sure what significance this has, but I hope it can maybe shed some light.

**Comment by TheKronks** [comment]
I've been a bit busy, but the change causing issues is simply the SlotObject field being changed from a short to an int, I'll make a commit tomorrow or someone else can.
Also, if you have an old client you want to use that doesnt have these changes implemented, you can simply read as a short and write as an int.
